(function(){var g=true,i;function k(){var a=l(),b;if(a)b=a._cb_cp,a._cb_cp="";else if(/_cb_cp[a-z0-9]{16}/.test(window.name))b=window.name.substr(6),window.name="";return b};function m(){this.a=window._sf_async_config||{};this.z=o(this,this.D);this.e=[];p(this);s("unload",o(this,this.C));for(var a=0,b;b=(window._cbq||[])[a];++a)this.t(b);window._cbq={push:o(this,this.t)}}i=m.prototype;i.t=function(a){this.a[a[0]]=a[1];this.f=0};function o(a,b){return function(){b.apply(a,arguments)}}function t(){var a,b,c;a="";for(c=0;c<16;c++)b=Math.floor(Math.random()*36).toString(36),a+=b;return a}
function u(a){var b={};if(a){a.charAt(0)=="?"&&(a=a.substring(1));for(var a=a.replace("+"," "),a=a.split(/[&;]/g),c=0;c<a.length;c++){var d=a[c].split("=");b[decodeURIComponent(d[0])]=decodeURIComponent(d[1])}}return b}function x(a,b,c,d){var e="",f=window.location.href.split("?");f.length&&(f=u(f[1]),a=a.a[d]||c,f[a]&&(e="&"+b+"="+f[a]));return e}function y(a,b,c){a.a[b]=a.a[b]||c}
function z(a){if(!A("_SUPERFLY_nosample"))a.A?a.l():(a.A=g,!window._sf_async_config&&!window._cbq?s("load",o(a,a.l)):a.l())}
function p(a){a.f=0;a.k=0;a.n=0;a.u=B();a.m=g;a.i=null;a.p=72E5;for(var b=document.getElementsByTagName("script"),c=0;c<b.length;c++)if(b[c].src.match(/(chartbeat|chartbeatdev|chartbeat_raw).js/)){var d=b[c];break}d&&(b=u(d.src.split("?")[1]),y(a,"uid",b.uid),y(a,"domain",b.domain));b=window.location;y(a,"pingServer","ping.chartbeat.net");y(a,"title",document.title);y(a,"domain",b.host);a:{c=null;if(a.a.useCanonical){for(var c=null,d=document.getElementsByTagName("link"),e=0;e<d.length;++e)if(d[e].rel==
"canonical")c=d[e].href,c=c.substring(c.indexOf("/",9));if(c)break a}e=window.location;c=e.pathname+(e.search||"");c=c.replace(/PHPSESSID=[^&]+/,"");d=/&utm_[^=]+=[^&]+/ig;(e=d.exec(e.search))&&(c=c.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(e=d.exec(c))&&(c=c.replace(d,e[1]!=""?"?"+e[1]:""))}y(a,"path",c);c=parseInt(a.a.sessionLength,10);if(!isNaN(c))a.p=c*6E4;a.s=t();a.o=b.host;a.o=a.o.replace(/^www\./,"");a.a.domain=a.a.domain.replace(/^www\./,"");a.g=A("_chartbeat2");b=B()-parseInt((a.g||"").split(".")[1]||
0,10);a.B=a.g&&b>18E5?0:1;if(!a.g)a.g=t()+"."+B();C("_chartbeat2",a.g,30);a.c?D(a.c):a.c=new E}i.F=function(a,b){this.v=window.location.protocol+"//"+this.a.domain+this.a.path;this.a.path=a;b&&(this.a.title=b);window.clearInterval(this.j);p(this);z(this)};i.w=function(a){this.i=a};i.l=function(){var a=window._sf_startpt,b=window._sf_endpt;if(typeof a=="number")this.r=typeof b=="number"?b-a:B()-a;this.j=window.setInterval(o(this,this.q),15E3);this.q()};
i.C=function(){var a=this.s,b=l();if(b)b._cb_cp+=(b._cb_cp?",":"")+a;else if(!window.name)window.name="_cb_cp"+a};function F(a,b){var c;c=new Image(1,1);c.onerror=a.z;c.src=b}i.D=function(){this.e.push(1);for(var a=0,b=0;b<this.e.length;++b)a+=this.e[b];a<3?(this.m=g,G(this)):(clearInterval(this.j),C("_SUPERFLY_nosample","1",0.0070))};function G(a){var b=a.f,b=b?Math.min(b*2,16):1;a.f=b}
i.q=function(){var a;a:{a=this.c;for(var b=0;b<a.h.length;b++)if(a.b[a.d][a.h[b]]){a=g;break a}a=false}H(this.c);this.k<this.f&&!a?this.k++:(a?(this.f=0,this.n+=15):G(this),this.k=0,J(this),B()-this.u>=this.p&&window.clearInterval(this.j))};function K(){var a=window,b=document.body,c=document.documentElement;if(typeof a.pageYOffset=="number")return a.pageYOffset;else if(b&&b.scrollTop)return b.scrollTop;else if(c&&c.scrollTop)return c.scrollTop;return 0}
function J(a){function b(a,b,c){return(b=j[b]||j[c])?"&g"+a+"="+encodeURIComponent(b):""}var c=K(),d=0,e=0,f=0,I=Math.round((B()-a.u)/600)/100;L(a.c,"onkeydown")?e=1:L(a.c,"onmousemove")||L(a.c,"onscroll")||I<0.1?d=1:f=1;var j=a.a,n="",h="",v=window.location;if(a.m)a.m=false,a.v?(n=a.v,h=g):(n=document.referrer||"",h=n.indexOf("://"+v.host+"/"),h=h!=-1&&h<9),n=(h?"&v=":"&r=")+encodeURIComponent(n),h="&i="+M(j.title.slice(0,100));var T=a.r?"&b="+a.r:"",U=a.i?"&A="+a.i:"",q=k(),q=q?"&D="+q:"";a.e.push(0);
a.e.length>18&&a.e.shift();var w=[],r;for(r in a.a)r[0]=="_"&&w.push(r+"="+a.a[r]);F(a,(v.protocol||"http:")+"//"+j.pingServer+"/ping?h="+encodeURIComponent(j.domain)+"&p="+encodeURIComponent(j.path)+"&u="+a.g+"&d="+M(v.host.replace(/^www\./,""))+"&g="+j.uid+b(0,"sections","categories")+b(1,"authors","brands")+"&n="+a.B+"&c="+I+"&x="+c+"&y="+(document.body.scrollHeight||0)+"&w="+(window.innerHeight||document.body.offsetHeight||0)+"&j="+Math.round((a.f+2)*15E3/1E3)+"&R="+d+"&W="+e+"&I="+f+"&E="+a.n+
n+T+U+x(a,"C","utm_campaign","campaignTag")+x(a,"M","utm_medium","mediumTag")+"&t="+a.s+"&V=2"+q+h+(w.length?"&"+w.join("&"):"")+"&_")};function E(){this.h=[];N(this,window,"onscroll");N(this,document.body,"onkeydown");N(this,document.body,"onmousemove");D(this)}function D(a){a.b=[{},{},{},{}];a.d=0;H(a)}function N(a,b,c){var d=b[c]||function(){};a.h.push(c);b[c]=function(b){d.apply(this,arguments);if(b&&c=="onkeydown"){var f=b.keyCode?b.keyCode:b.which;if(f==32||f>36&&f<41){a.b[a.d].onscroll++;return}}a.b[a.d][c]++}}function L(a,b){for(var c=0,d=0;d<a.b.length;d++)c+=a.b[d][b]||0;return c}
function H(a){a.d=(a.d+1)%a.b.length;for(var b=0;b<a.h.length;b++)a.b[a.d][a.h[b]]=0};function A(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++){for(var d=b[c];d.charAt(0)==" ";)d=d.substring(1,d.length);if(d.indexOf(a)==0)return d.substring(a.length,d.length)}return null}function C(a,b,c){var d=new Date;d.setTime(B()+c*864E5);document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"};function l(){if(O!==void 0)return O;try{var a=window.localStorage;if(a.removeItem)return O=a}catch(b){}return O=null}var O;function s(a,b){var c=window;c.addEventListener?c.addEventListener(a,b,false):c.attachEvent&&c.attachEvent("on"+a,b)}function B(){return(new Date).getTime()}function M(a){return encodeURIComponent(a)};function P(a){var b=document.createElement("script");b.async=g;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)}function Q(a){if(/[\/|\.]chartbeat.com$/.test(a.origin)){var b=l(),c=String(a.data);if(b&&c.indexOf("_cb_ip")==0)c=c.substr(6),b._cb_ip=c,a.source.postMessage(1,a.origin),c&&P(c)}};var R=new m;window.pSUPERFLY=R;m.prototype.virtualPage=m.prototype.F;m.prototype.activity=m.prototype.w;z(R);var S=l();if(S){s("message",Q);var V=S._cb_ip;V&&P(V)};})();
